---
title: "data manipulation"
output: git_document
date: "2022-09-22"
---
```{r}
library(tidyverse)
```



```{r}
litters_data= read_csv("Data/data/FAS_litters.csv")
litters_data= janitor:: clean_names(litters_data)
view(litters_data)
```
## 'select'

Choose some columns and not others

```{r}
select(litters_data, group, gd0_weight)

```

```{r}
select(litters_data, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_data, -pups_survive)
```
Renaming columns...

```{r}
rename(litters_data, GROUP=group...)
```
```{r}
select(litters_data, starts_with("gd"))
select(litters_data, ends_with("weight"))
```
```{r}
select(litters_data, litter_number, pups_survive, everyhing())
```
```{r}
filter(litters_data, gd0_weight >=22, gd_of_birth ==20)
```
```{r}
filter(litters_data, group %in% c("Con7","Mod8"))
```
```{r}
mutate(
  litters_data, 
  wt_gain =gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## 'arrange'

```{r}
arrange(litters_data, pups_born_alive)
```

```{r}
arrange(litters_data, pups_born_alive, gd0_weight)

```
## '%>%'

```{r}
litters_data_raw = read_csv("Data/data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select (litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_Gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```
USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df =
  read_csv("./Data/data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(wt_gain = gd18_weight - gd0_weight) %>%
  drop_na(gd0_weight)
```

