---
title: "Data Import"
output: github_document
---


```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

##Data Imports: CSVs 

Let's import data using the `readr`

```{r}
litters_df = read_csv("Data/data/FAS_litters.csv")
litter_df = janitor::clean_names(litters_df)
```

## Take a look at the data

printing in the console.

```{r}
litters_df
```

```{r}
skimr::skim(litter_df)
```
## Options to read_csv 

```{r}
read_csv("Data/data/FAS_litters.csv", na = c("", 999, 88), skip = 10, col_names = FALSE)
```
Look at the data

```{r}
litters_df
```
##Other file formats

we need to read in an excel file

```{r}
mlb_df = read_excel("Data/data/mlb11.xlsx", range = "A1:F7")
```

```{r, eval =FALSE}
view(mlb_df)
```
```{r}
lotr_words_df = 
    read_excel(
      "Data/data/LotR_Words.xlsx",
      range = "B3:D6"
    )
```
Read in a SAS dataset. 

```{r}
pulse_df = read_sas("Data/data/public_pulse_data.sas7bdat")
pulse_df
```
## Comparison with Base R 

What about 'read.csv'...? 

```{r}
litters_base = read.csv("Data/data/FAS_litters.csv")
litters_readr = read_csv("Data/data/FAS_litters.csv")

litters_base
litters_readr
```

##Exporting data 
```{r}
write_csv(lotr_words_df, file = "lotr_words.csv"
)
```
